---
title: "Predict accident type"
output: html_notebook
---
 

# Directories
```{r}
#Data
d.rp <- "B:/0_UtypPaper/0_RP/"

#Results
ergebnisse <- "B:/0_UtypPaper/2_Ergebnisse/"

#Images
abbildungen <- "B:/0_UtypPaper/3_Abbildungen/"

#Convert factors to numeric values

as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
```

# (1) Read

```{r Read in}
#List with all accident data in the directory
l.rp <- list.files(d.rp, pattern = "*.xlsx", all.files = TRUE, full.names = TRUE)

#Read each file on list as Excel
e.rp <- lapply(l.rp, readxl::read_excel)

#Create a complete file
g.rp <- data.table::rbindlist(e.rp)

#Filter for turning accidents 
abb.rp <- dplyr::filter(g.rp, g.rp$`VU-Typ` == "Abbiegeunfall")


#Filter by accidents participant 1 = passenger car with and without personal injury
abb.rp <- dplyr::filter(abb.rp, abb.rp$`ON 1` == "Personenkraftwagen")

#Filter for accidents with personal injury and Bet. 1 = passenger car:
abb.rp1 <- dplyr::filter(abb.rp, abb.rp$`VU-Kategorie` == "1 - Unfall mit Getöteten") 
abb.rp2 <- dplyr::filter(abb.rp, abb.rp$`VU-Kategorie` == "2 - Unfall mit Schwerverletzten") 
abb.rp3 <- dplyr::filter(abb.rp, abb.rp$`VU-Kategorie` == "3 - Unfall mit Leichtverletzten") 

abb.rpg <- rbind(abb.rp1, abb.rp2, abb.rp3) #7622 Unfaelle 

#Comparison with accident type catalog list 
udv <- c(201,202,203,204,209, 211,212,213,214,215,219, 221,222,223,224,225,229, 231,232,233,239, 241,242,243,244,245,249, 251,252,259, 261,262,269, 271,272,273,274,275,279, 281,282,283,284,285,286,289, 299)
length(udv)

abb.rpg$`VU-Typ-Nr.` <- as.integer(abb.rpg$`VU-Typ-Nr.`)
abb.rpg2 <- dplyr::filter(abb.rpg, `VU-Typ-Nr.` %in% udv )

#Speichern
saveRDS(abb.rpg2, paste(ergebnisse, "00_RP_Unfalltyp2.rds"))

```


# (2) Prepare variables 

```{r Variables}
#46 variables given 
str(abb.rpg2)
abb.rpg2 <- readRDS(paste(ergebnisse, "00_RP_Unfalltyp2.rds"))

#Remove variables not needed or contained twice in the data-set 
abb.s <- dplyr::select(abb.rpg2, -`VU-Kategorie`, -Datum, -Hausnr., -`Kreuzung/Einmündung`, -Strassennummer, -Buchstabe, -Netzknoten, -Station, -Buchstaben, -`VU-Typ`, -Unfallart)


#Remaining variables: Zeit, wochentag, Ort, straße, Ortslage, GPSx, GPSy, Strassenklasse, Unfalltyp, Unfallart, witterung, Rad-/Gehweg, Hindernis, LZA an/aus, Geschw-Begr., Lichtverh., Strassenverhl., Ursache 70-89, Get., SV, LV, Gesamtschaden, Alkohol, Drogen, Medikamente, Unfallflucht, ON1, Alter ON1, Verletzungsgrad on1, ursache 01-69 ON1, Fehler beim abbiegen, ON2, Alter ON2, Verletzungsgrad ON2, ursache 01-69 on 2, Unfallhergang 

#Prepare 35 variables 

#Time 
abb.s$Year <- substr(abb.s$Zeit, 1,4)
abb.s$Month <- substr(abb.s$Zeit, 6, 7) #Monat
abb.s$HourMinute <- paste(substr(abb.s$Zeit, 12, 13), substr(abb.s$Zeit, 15,16), sep = "") #StundeMinute
abb.s$Hour <- substr(abb.s$Zeit, 12, 13)
abb.s$Hour <- as.factor(abb.s$Hour)
abb.s <- dplyr::select(abb.s, -Zeit)


#Local Area
abb.s$Urban <- ifelse(abb.s$`igO/agO` == "innerorts", 1, 0)
abb.s$Rural <- ifelse(abb.s$`igO/agO` == "außerorts", 1, 0)
abb.s <- dplyr::select(abb.s, -`igO/agO`)
abb.s$Urban <- as.factor(abb.s$Urban)
abb.s$Rural <- as.factor(abb.s$Rural)

#Cycle Path / Sidewalk 
abb.s$CyclePath <- ifelse(abb.s$`Rad-/Gehweg` == "Radweg", 1, 0)
abb.s$Sidewalk <- ifelse(abb.s$`Rad-/Gehweg` == "Gehweg", 1, 0)
abb.s <- dplyr::select(abb.s, -`Rad-/Gehweg`)
abb.s$CyclePath <- as.factor(abb.s$CyclePath)
abb.s$Sidewalk <- as.factor(abb.s$CyclePath)

#Traffic light 
abb.s$TrafficLightOn <- ifelse(abb.s$`LZA an/aus` == "in Betrieb", 1, 0) #in Betrieb
abb.s$TrafficLightOff <- ifelse(abb.s$`LZA an/aus` == "außer Betrieb", 1, 0) #ausser Betrieb
abb.s <- dplyr::select(abb.s, -`LZA an/aus`)
abb.s$TrafficLightOn <- as.factor(abb.s$TrafficLightOn)
abb.s$TrafficLightOff <- as.factor(abb.s$TrafficLightOff)

#Alcohol 
abb.s$Alcohol <- ifelse(abb.s$Alkohol == "ja", 1, 0)
abb.s <- dplyr::select(abb.s, -Alkohol)
abb.s$Alcohol <- as.factor(abb.s$Alcohol)

#Drugs
abb.s$Drugs <- ifelse(abb.s$Drogen == "ja", 1, 0)
abb.s <- dplyr::select(abb.s, -Drogen)
abb.s$Drugs <- as.factor(abb.s$Drugs)

#Medicine
abb.s$Medicines <- ifelse(abb.s$Medikamente == "ja", 1, 0)
abb.s <- dplyr::select(abb.s, -Medikamente)
abb.s$Medicines <- as.factor(abb.s$Medicines)

#Hit and run 
abb.s$HitAndRun <- ifelse(abb.s$Unfallflucht == "ja", 1, 0)
abb.s <- dplyr::select(abb.s, -Unfallflucht)
abb.s$HitAndRun <- as.factor(abb.s$HitAndRun)

#WordCount 
abb.s$WordCount <- lengths(gregexpr("\\W+", abb.s$Unfallhergang)) + 1

#TextLength 
abb.s$TextLength <- nchar(abb.s$Unfallhergang)


#Add new variable 2AT (AccidentType2)
abb.s$AccidentType2 <- substr(abb.s$`VU-Typ-Nr.`, 1, 2)


#Add ID column for later identification 
abb.s <- tibble::rowid_to_column(abb.s, "ID")


#Rename variables 
colnames(abb.s) <- c("ID", "Weekday", "Location", "Street", "Long", "Lat", "StreetClass", "AccidentType", "CollisionType", "Weather", "Obstacle", "SpeedLimit", "LightCondition", "RoadCondition", "Cause", "Killed", "SeriouslyInjured", "LightlyInjured", "PropertyDamage", "Participant1", "AgeP1", "InjuryP1", "CauseP1", "Participant2", "AgeP2", "InjuryP2", "CauseP2", "Description", "Year", "Month", "HourMinute", "Hour", "Urban", "Rural", "CyclePath", "Sidewalk", "TrafficLightOn", "TrafficLightOff", "Alcohol", "Drugs", "Medicines", "HitAndRun", "WordCount", "TextLength", "AccidentType2" )



#Save
abb.s1 <- abb.s


#Align/rename factor levels 
#Weekday
abb.s1$Weekday <- as.factor(abb.s1$Weekday)
abb.s1$Weekday <- plyr::revalue(abb.s1$Weekday, c("Di" = "Tue", "Do" = "Thu", "Fr" = "Fri", "Mi" = "Wed", "Mo" = "Mon", "Sa" = "Sat", "So" = "Sun"))


#Street class
abb.s1$StreetClass <- plyr::revalue(abb.s1$StreetClass, c("Landesstraße" = "Country", "Kreisstraße" = "County", "Bundesstraße" = "State", "andere Straße" = "Other", "Autobahn" = "Highway"))
abb.s1$StreetClass <- as.factor(abb.s1$StreetClass)

#AccidentType
abb.s1$AccidentType <- as.factor(abb.s1$AccidentType)
abb.s1$AccidentType2 <- as.factor(abb.s1$AccidentType2)

#CollisionType
abb.s1$CollisionType <- as.factor(abb.s1$CollisionType)
#--> CollisionType ist um 1 verschoben zu EUSKA-Export codiert. 
#--> 1 = Unfall anderer Art, 2 = Zusammenstoß mit anfahrendem Fzg., 3 = Zusammenstoß mit vorausfahrendem Fzg., 4 = Zusammenstoß mit seitlich gleicher Richtung, 5 = Zusammenstoß mit entgegenkommenden, 6 = Zusammenstoß mit einbiegenden, 7 = Zusammenstoß zwischen Fzg. und Fußgänger, 8 = Aufprall auf Fahrbahnhindernis, 9 = Abkommen von Fahrbahn nach rechts, 10 = Abkommen von Fahrbahn nach links 


#Weather
abb.s1$Weather <- plyr::revalue(abb.s1$Weather, c("Nebel / Dunst (Sicht ca.)" = "Fog", "Regen" = "Rain", "Sturm / Böen" = "Storm", "Schneefall / Hagel" = "Snowfall" ))
abb.s1$Weather <- as.factor(abb.s1$Weather)

#Obstacle
abb.s1$Obstacle <- plyr::revalue(abb.s1$Obstacle, c("Baum" = "Tree", "kein Aufprall" = "No", "sonstiges Hindernis" = "Other", "Mast" = "Mast", "Schutzplanke" = "Barrier", "Widerlager" = "Abutment"))
abb.s1$Obstacle <- as.factor(abb.s1$Obstacle)

#SpeedLimit
abb.s1$SpeedLimit <- plyr::revalue(abb.s1$SpeedLimit, c("/" = "NA", "070" = "70", "4-7" = "7", "Z07" = "Z7", "z30" = "Z30"))
abb.s1$SpeedLimit <- as.factor(abb.s1$SpeedLimit)
abb.s1$SpeedLimit <- abb.s1 %>% select(SpeedLimit) %>% mutate(SpeedLimit = na_if(SpeedLimit, "NA"))
abb.s1$SpeedLimit <- droplevels(abb.s1$SpeedLimit)

#LightCondition
abb.s1$LightCondition <- plyr::revalue(abb.s1$LightCondition, c("Dämmerung" = "Twilight", "Dunkelheit" = "Darkness", "Tageslicht" = "Daylight"))
abb.s1$LightCondition <- as.factor(abb.s1$LightCondition)

#RoadCondition
abb.s1$RoadCondition <- as.factor(abb.s1$RoadCondition)
abb.s1$RoadCondition <- gsub(pattern = '[Ö]', replacement = "Oe", abb.s1$RoadCondition)
abb.s1$RoadCondition <- gsub(pattern = '[ü]', replacement = "ue", abb.s1$RoadCondition)
abb.s1$RoadCondition <- plyr::revalue(abb.s1$RoadCondition, c("nass / feucht" = "wet","schluepfrig (Oel, Dung, Laub, usw.)" = "slippery", "trocken" = "dry", "winterglatt" = "winter-slick"))
abb.s1$RoadCondition <- as.factor(abb.s1$RoadCondition)


#Cause
abb.s1$Cause <- plyr::revalue(abb.s1$Cause, c("Unwetter oder sonstige Witterungseinflüsse" = "Thunderstorms", "Sonstiges Hindernis auf der Fahrbahn" = "Other_Obstacles", "Sonstige Ursachen" = "Other_Causes", "Sichtbehinderung durch starken Regen, Hagel, Schneegestöber usw." = "ImpairedVisibility_Weather", "Sichtbehinderung durch Nebel" = "ImpairedVisibility_Fog", "Sichtbehinderung durch blendende Sonne" = "ImpairedVisibility_Sun", "Schnee, Eis" = "Snow_Ice", "Regen" = "Rain", "Nicht ordnungsgemäßer Zustand der Verkehrszeichen oder Verkehrseinrichtungen" = "Infrastructure", "Mangelhafte Beleuchtung der Straße" = "Bad_Lighting", "Andere Einflüsse wie Laub, angeschlemmter Lehm" = "Other_Leach_SmearedClay", "Sonstige Ursachen (kurze Beschreibung im Sachverhalt)" = "Other"))
abb.s1$Cause <- as.factor(abb.s1$Cause)


#PropertyDamage
abb.s1$PropertyDamage <- stringr::str_replace_all(abb.s1$PropertyDamage, "[^[:alnum:]]", " ") #Entfernt das Euro-Zeichen
abb.s1$PropertyDamage <- as.numeric(abb.s1$PropertyDamage) #Umwandlung in numerischen Wert


#Participant1
abb.s1$Participant1 <- plyr::revalue(abb.s1$Participant1, c("Personenkraftwagen" = "Car"))
abb.s1$Participant1 <- as.factor(abb.s1$Participant1)


#AgeP1
abb.s1$AgeP1 <- as.numeric(abb.s1$AgeP1)

#AgeP2
abb.s1$AgeP2 <- as.numeric(abb.s1$AgeP2)

#InjuryP1
abb.s1$InjuryP1 <- plyr::revalue(abb.s1$InjuryP1, c("tödlich verletzt" = "fatally", "leicht verletzt" = "slightly", "schwer verletzt" = "seriously"))
abb.s1$InjuryP1 <- as.factor(abb.s1$InjuryP1)

#InjuryP2
abb.s1$InjuryP2 <- plyr::revalue(abb.s1$InjuryP2, c("tödlich verletzt" = "fatally", "leicht verletzt" = "slightly", "schwer verletzt" = "seriously"))
abb.s1$InjuryP2 <- as.factor(abb.s1$InjuryP2)

#CauseP1
abb.s1$CauseP1 <- plyr::revalue(abb.s1$CauseP1, c("Überholen trotz unklarer Verkehrslage" = "1", "Fehler beim Abbiegen (§ 9) (ausgenommen Pos. 33, 40)" = "2", "Nichtbeachten der Vorfahrt des durchgehenden Verkehrs (§ 18 III)" = "3", "Fehler beim Abbiegen (§ 9) nach links (ausgen. Pos. 33, 40)" = "4", "Verbotswidrige Benutzung der Fahrbahn oder anderer Straßenteile (z.B. Gehweg, Radweg)" = "5", "Falsches Verhalten ggü. Fußgängern beim Abbiegen" = "6", "Nicht angepasste Geschwindigkeit in anderen Fällen" = "7", "Nichtbeachten der die Vorfahrt regelnden Verkehrszeichen" = "8", "Fehler beim Einfahren in den fließenden Verkehr" ="9", "Nichtbeachten der Verkehrsregelung durch Polizeibeamte oder Lichtzeichen" = "10", "Nichtbeachten des Vorranges entgegenkommender Fahrzeuge  (Zeichen 208)" = "11", "Falsches Verhalten ggü. Fußgängern an Fußgängerfurten" = "12", "Ungenügender Sicherheitsabstand" = "13",  "Sonstige körperliche oder geistige Mängel" = "14", "Nichtbeachten des Vorranges entgegenkommender Fahrzeuge beim Vorbeifahren" = "15", "Sonstige Fehler beim Überholen" = "16", "Einfluß anderer berauschender Mittel (z.B. Drogen, Rauschgift)" = "17",  "Alkoholeinfluß" = "18", "Benutzung der falschen Fahrbahn oder verbotswidrige Benutzung anderer Straßenteile" = "19", "Verstoß gegen das Rechtsfahrgebot" = "20", "Falsches Verhalten ggü. Fußgängern an Fußgängerüberwegen" = "21", "Nicht angepasste Geschwindigkeit mit gleichzeitigem Überschreiten der zulässigen Höchstgeschwindigkeit" = "22",  "Falsches Verhalten ggü. Fußgängern an anderen Stellen" = "23", "Fehler beim Abbiegen (§ 9) nach rechts (ausgen. Pos. 33, 40)" = "24", "Fehler beim Wiedereinordnen nach rechts" = "25",  "Andere Fehler beim Fahrzeugführer" = "26", "Nichtbeachten des Vorranges von Schienenfahrzeugen an Bahnübergängen" = "27", "Fehlerhaftes Wechseln des Fahrstreifens beim Nebeneinanderfahren" = "28", "Fehler beim Wenden oder Rückwärtsfahren" = "29", "Nichtbeachten der Regel \"rechts vor links\"" = "30", "Fehler beim Überholtwerden" = "31","Übermüdung" = "32",  "Starkes Bremsen des Vorausfahrenden ohne zwingenden Grund" = "33", "Benutzung der Fahrbahn entgegen der vorgeschriebenen Fahrtrichtung in anderen Fällen (Stichwort „Einbahnstraße“)" = "34", "Falschfahrt auf Straßen mit nach Fahrtrichtung getrennten Fahrbahnen (Stichwort „Falschfahrer“)" = "35", "Überholen ohne Beachtung des nachfolgenden Verkehrs oder rechtzeitige Ankündigung des Ausscherens" = "36", "Nichtbeachten des nachfolgenden Verkehrs beim Vorbeifahren" = "37", "Verkehrswidriges Verhalten beim Ein-/Aussteigen, Be-/Entladen" = "38", "Unzulässiges Rechtsüberholen" = "39", "Andere Mängel" = "40" ))
abb.s1$CauseP1 <- as.factor(abb.s1$CauseP1)


#CauseP2
abb.s1$CauseP2 <- plyr::revalue(abb.s1$CauseP2, c("Überholen trotz unklarer Verkehrslage" = "1", "Fehler beim Abbiegen (§ 9) (ausgenommen Pos. 33, 40)" = "2", "Nichtbeachten der Vorfahrt des durchgehenden Verkehrs (§ 18 III)" = "3", "Fehler beim Abbiegen (§ 9) nach links (ausgen. Pos. 33, 40)" = "4", "Verbotswidrige Benutzung der Fahrbahn oder anderer Straßenteile (z.B. Gehweg, Radweg)" = "5", "Falsches Verhalten ggü. Fußgängern beim Abbiegen" = "6", "Nicht angepasste Geschwindigkeit in anderen Fällen" = "7", "Nichtbeachten der die Vorfahrt regelnden Verkehrszeichen" = "8", "Fehler beim Einfahren in den fließenden Verkehr" ="9", "Nichtbeachten der Verkehrsregelung durch Polizeibeamte oder Lichtzeichen" = "10", "Nichtbeachten des Vorranges entgegenkommender Fahrzeuge  (Zeichen 208)" = "11", "Falsches Verhalten ggü. Fußgängern an Fußgängerfurten" = "12", "Ungenügender Sicherheitsabstand" = "13",  "Sonstige körperliche oder geistige Mängel" = "14", "Nichtbeachten des Vorranges entgegenkommender Fahrzeuge beim Vorbeifahren" = "15", "Sonstige Fehler beim Überholen" = "16", "Einfluß anderer berauschender Mittel (z.B. Drogen, Rauschgift)" = "17",  "Alkoholeinfluß" = "18", "Benutzung der falschen Fahrbahn oder verbotswidrige Benutzung anderer Straßenteile" = "19", "Verstoß gegen das Rechtsfahrgebot" = "20", "Falsches Verhalten ggü. Fußgängern an Fußgängerüberwegen" = "21", "Nicht angepasste Geschwindigkeit mit gleichzeitigem Überschreiten der zulässigen Höchstgeschwindigkeit" = "22",  "Falsches Verhalten ggü. Fußgängern an anderen Stellen" = "23", "Fehler beim Abbiegen (§ 9) nach rechts (ausgen. Pos. 33, 40)" = "24", "Fehler beim Wiedereinordnen nach rechts" = "25",  "Andere Fehler beim Fahrzeugführer" = "26", "Nichtbeachten des Vorranges von Schienenfahrzeugen an Bahnübergängen" = "27", "Fehlerhaftes Wechseln des Fahrstreifens beim Nebeneinanderfahren" = "28", "Fehler beim Wenden oder Rückwärtsfahren" = "29", "Nichtbeachten der Regel \"rechts vor links\"" = "30", "Fehler beim Überholtwerden" = "31","Übermüdung" = "32",  "Starkes Bremsen des Vorausfahrenden ohne zwingenden Grund" = "33", "Benutzung der Fahrbahn entgegen der vorgeschriebenen Fahrtrichtung in anderen Fällen (Stichwort „Einbahnstraße“)" = "34", "Falschfahrt auf Straßen mit nach Fahrtrichtung getrennten Fahrbahnen (Stichwort „Falschfahrer“)" = "35", "Überholen ohne Beachtung des nachfolgenden Verkehrs oder rechtzeitige Ankündigung des Ausscherens" = "36", "Nichtbeachten des nachfolgenden Verkehrs beim Vorbeifahren" = "37", "Verkehrswidriges Verhalten beim Ein-/Aussteigen, Be-/Entladen" = "38", "Unzulässiges Rechtsüberholen" = "39", "Andere Mängel" = "40", "Falsches Fahrbahnüberschreiten ohne Beachtung des Fahrzeugverkehrs" = "41", "Andere Fehler der Fußgänger" = "42", "Falsches Fahrbahnüberschreiten durch plötzliches Hervortreten hinter Sichthindernis" = "43", "Mängel, Beleuchtung" = "44", "Falsches Fahrbahnüberschreiten in der Nähe von LZA oder Überwegen" = "45", "Unzulässiges Halten oder Parken" = "46", "Nichtbeachten der Beleuchtungsvorschriften (ausgenommen Pos. 50)" = "47", "Falsches Fahrbahnüberschreiten durch sonstiges falsches Verhalten" = "48","Falsches Fahrbahnüberschreiten bei Regelung durch Polizei oder Lichtzeichen" = "49", "Mängel, Bremsen" = "50", "Falsches überschreiten des Fußgängerüberweges ohne Verkehrsregelung" = "51"  ))
abb.s1$CauseP2 <- as.factor(abb.s1$CauseP2)

#Participant2
abb.s1$Participant2 <- plyr::revalue(abb.s1$Participant2, c("Personenkraftwagen" = "Car1", "Kraftrad über 125 ccm oder Nennleistung über 11 KW" = "PTW5", "Leichtkraftrad über 50 bis 125 ccm und Nennleistung bis 11 KW" = "PTW3", "Fahrrad" = "Bicylce1", "Fußgänger" = "Ped1", "Liefer- und Lastkraftwagen, Gesamtgewicht bis 3,5 t ohne Anhänger" = "Truck1", "Kleinkraftrad bis 50 ccm und bis 50 km/h" = "PTW2", "Mofa 25, Fahrrad mit Hilfsmotor bis 50 ccm und bis 25 km/h" = "PTW1", "Sattelzugmaschine, auch mit Auflieger" = "Truck_2", "Kraftroller/Motorroller über 125 ccm oder Nennleistung über 11 KW" = "PTW4", "Schulbus" = "Bus1", "Fußgänger mit Sport- oder Spielgerät" = "Ped2","Landwirtschaftliche Zugmaschine, auch mit Anhänger" = "Tractor1", "Liefer- und Lastkraftwagen, Gesamtgewicht über 3,5 t ohne Anhänger" = "Truck3", "Pedelec (ohne Kennzeichen)" ="Bicycle2", "S-Pedelec (mit Kennzeichen)" = "Bicycle3", "Straßenbahn" = "Tram", "Liefer- und Lastkraftwagen, Gesamtgewicht über 3,5 t mit Anhänger" = "Truck4", "Leichtes drei- und vierrädriges Kraftfahrzeug" = "3/4Wheels", "Drei- und leichtes vierrädriges Kraftfahrzeug" = "3/4Wheels", "Lastkraftwagen mit Spezialaufbau" = "Truck5","Übrige Kraftfahrzeuge, bis 31.12.2019 auch Elektrokleinstfahrzeuge" ="Car2", "Tierführer, Treiber" = "Ped3", "Andere Zugmaschine, auch mit Anhänger" = "Truck6","Liefer- und Lastkraftwagen, Gesamtgewicht bis 3,5 t mit Anhänger" = "Truck7", "Sonstiges und unbekanntes Fahrzeug" = "OtherVehicle", "Andere Personen" = "Ped4", "Sattelzugmaschine mit Auflieger als Tankwagen" = "Truck8", "Linienbus" = "Bus2" ))
abb.s1$Participant2 <- as.factor(abb.s1$Participant2)


#Year
abb.s1$Year <- as.factor(abb.s1$Year)

#Month
abb.s1$Month <- as.factor(abb.s1$Month)


#Save
saveRDS(abb.s1, paste(ergebnisse, "01_RP_Unfalltyp2.rds"))
write.csv(abb.s1, paste(ergebnisse, "01_RP_Unfalltyp2.csv"))


abb.s2 <- dplyr::select(abb.s1, ID, AccidentType2, AccidentType, Year, Month, Weekday, Hour, Urban, Rural, StreetClass, RoadCondition, LightCondition, Weather, Obstacle, CyclePath, Sidewalk, TrafficLightOn, TrafficLightOff, Alcohol, Drugs, Medicines, HitAndRun, CollisionType, Cause, Participant1, InjuryP1, CauseP1, Participant2, InjuryP2, CauseP2, Killed, SeriouslyInjured, LightlyInjured, SpeedLimit, AgeP1, AgeP2, PropertyDamage, WordCount, TextLength, HourMinute)


#Save
saveRDS(abb.s2, paste(ergebnisse, "02_RP_Unfalltyp2.rds"))



```

# (3) Libraries

```{r Libraries}
#Libraries
library(dplyr)
library(forcats)
library(tidyr)
library(StatMatch)
library(ggplot2)


#Datei
#abb.s2 <- readRDS(paste(ergebnisse, " 02_RP_Unfalltyp2.rds", sep =""))


```


# (4) Exploratory Data analysis: Correlation Plots 

```{r Correlation}
#Theils U Correlation Plot 

#Liste mit 2ATs
types <- list(20, 21, 22, 23, 24, 25, 26, 27, 28, 29)


theils <- function(daten, typ){

library(StatMatch)
library(data.table)
library(dplyr)
library(forcats)
  
u <- as.data.frame(daten) 

#Entfernen der ID-Spalte
u <- dplyr::select(u, -ID)
  
#Kategorisieren der numerischen variablen (ansonsten wird Theils U nicht korrekt berechnet)

#Killed
u$Killed <- as.factor(u$Killed)
#SeriouslyInjured
u$SeriouslyInjured <- as.factor(u$SeriouslyInjured)
#LightlyInjured
u$LightlyInjured <- as.factor(u$LightlyInjured)
#AgeP1
u$AgeP1 <- forcats::fct_explicit_na(cut(u$AgeP1, breaks = c(-1,20, 40, 60,80, 150), labels = c("<20","20-40","40-60","60-80","<80")),"9999") #basierend auf Histogramm
#AgeP2
u$AgeP2 <- forcats::fct_explicit_na(cut(u$AgeP2, breaks = c(-1,20, 40, 60,80, 150), labels = c("<20","20-40","40-60","60-80","<80")),"9999") #basierend auf Histogramm
#PropertyDamage
u$PropertyDamage <- forcats::fct_explicit_na(cut(u$PropertyDamage, breaks = c(-1,2500, 5000, 10000, 15000,20000, 25000, 50000, 200000), labels = c("<2500", "2500-5000","5000-10000","10000-15000", "15000-20000", "20000-25000", "25000-50000",">50000")),"9999") #basierend auf Histogramm
#WordCount
u$WordCount <- forcats::fct_explicit_na(cut(u$WordCount, breaks = c(-1,50, 100, 150,200, 250, 500), labels = c("<50","50-100","100-150","150-200", "200-250",  ">500")),"9999") #basierend auf Histogramm 
#TextLength   
u$TextLength <- forcats::fct_explicit_na(cut(u$TextLength, breaks = c(-1,250, 500, 750, 1000, 1250,1500, 3000), labels = c("<250","250-500","500-750","750-1000", "1000-1250", "1250-1500", ">1500")),"9999") #basierend auf Histogramm   


#Code unknown values  
for (i in 1:length(u)){
  u[,i] <- forcats::fct_explicit_na(u[,i], "9999")
}

#Calculate Theils U 
u0 <- StatMatch::pw.assoc(AccidentType ~ Year+Month+Weekday+Hour+Urban+Rural+StreetClass+RoadCondition+LightCondition+Weather+Obstacle+CyclePath+Sidewalk+TrafficLightOn+TrafficLightOff+Alcohol+Drugs+Medicines+HitAndRun+CollisionType+Cause+Participant1+InjuryP1+CauseP1+Participant2+InjuryP2+CauseP2+as.factor(Killed)+SeriouslyInjured+LightlyInjured+SpeedLimit+AgeP1+AgeP2+PropertyDamage+WordCount+TextLength, data = u, out.df = TRUE )

#Rownames 
u1 <- data.table::setDT(u0, keep.rownames = "Variable")
u1 <- dplyr::select(u1, Variable, U)


#Filter for Theils U (>0,1)
u1$U <- round(u1$U, 3)
u1 <- dplyr::filter(u1, U >= 0.1 )


#Sort for descending U 
u1 <- u1[order(-U), ]


#Add AT 
u1$Typ <- typ


#Add variables with >0.1
u1$Number <- nrow(u1)

#Return 
return(u1)
}


#Analaysis
t.ges <- theils(abb.s2, "All")
t.20 <- theils(abb.s2[abb.s2$AccidentType2 == 20, ], 20)
t.21 <- theils(abb.s2[abb.s2$AccidentType2 == 21, ], 21)
t.22 <- theils(abb.s2[abb.s2$AccidentType2 == 22, ], 22)
t.23 <- theils(abb.s2[abb.s2$AccidentType2 == 23, ], 23)
t.24 <- theils(abb.s2[abb.s2$AccidentType2 == 24, ], 24)
t.25 <- theils(abb.s2[abb.s2$AccidentType2 == 25, ], 25) 
t.26 <- theils(abb.s2[abb.s2$AccidentType2 == 26, ], 26)
t.27 <- theils(abb.s2[abb.s2$AccidentType2 == 27, ], 27)
t.28 <- theils(abb.s2[abb.s2$AccidentType2 == 28, ], 28)
t.29 <- theils(abb.s2[abb.s2$AccidentType2 == 29, ], 29)


#Bind all U > 0.1 
tu.ges <- rbind(t.ges, t.20, t.21, t.22, t.23, t.24, t.25, t.26, t.27, t.28, t.29)
tu.ges <- tu.ges[order(-Number), ]



#Prepare for diagrams 
tu.c <- tu.ges %>% filter(Typ != "All") %>% count(Variable) 
tu.c <- tu.c[order(-n), ] 

#Diagram a
tu.a <- tu.ges %>%
  ggplot(mapping = aes(x = Typ, y = Number, color = Typ))+
  geom_point()+
  #Beschriftung 
  guides(fill = FALSE, color = FALSE)+ #Legende für Unfalltyp deaktiviert 
  scale_y_continuous(breaks = c(0,1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28))+
  geom_text(stat = 'identity', aes(label = Number), vjust = -0.5, hjust = -0.5, size = 3)+
  ylab("Frequency (Theil's U > 0.1)")+
  xlab("Accident Type (2 digits)")+
  #Polarkoordinaten
  coord_polar()


tu.a

#ggplot2::ggsave(tu.a, file = paste(abbildungen,"TheilsU_AccidentType_NumberVariables.png", sep = ""))


#Diagram b
tu.b <- tu.ges %>%
  ggplot(mapping = aes(x = Typ, y = Variable))+
  theme_bw()+
  #Punktgroesse in Abh. des berechneten Theil's U
  geom_point(aes(size = U))+
  scale_size_continuous(range = c(1,4), name ="Theil's U")+ #Groessenrange der einzelnen Punkte + Legendentitel
  #Beschriftung
  guides(color = FALSE)+ #Entfernung der Unfalltypen-Legende
  ylab("Variable (Theil's U > 0.1)")+
  xlab("Accident Type (2 digits, 2AT)")


tu.b

ggplot2::ggsave(tu.b, file = paste(abbildungen,"TheilsU_AccidentType_VariableDetailsUncolered_V2.png", sep = ""))




#Diagram c
#Diagramm c: 
tu.count <- tu.c %>%
  dplyr::mutate(Variable = forcats::fct_reorder(Variable, n)) %>% #Neuordnung, nach Anzahl 
  ggplot(mapping = aes(x= Variable, y = n))+
  theme_bw()+
  geom_col()+ #Saeulen 
  #Beschriftung
  ylim(0,10)+
  scale_y_continuous(breaks = c(0,1, 2,3, 4,5, 6,7, 8,9, 10))+
  xlab("Variable (Theil's U > 0.1)")+
  ylab("Frequency")+
  coord_flip()


tu.count


```


# (5) Exploratory Data analysis: Interesting notes: Manual data analysis by inspecting diagrams 


```{r Manual anomalies}

#Filtern for manually detected anomalies 


#203
at203.causep1 <- dplyr::filter(abb.s2, AccidentType == 203 & CauseP1 == "24")
at203 <- at203.causep1

#211
at211.causep1 <- dplyr::filter(abb.s2, AccidentType == 211 & CauseP1 == "24")
at211.causep2 <- dplyr::filter(abb.s2, AccidentType == 211 & CauseP2 == "24")
at211 <- plyr::join(at211.causep1, at211.causep2, by = "ID", type = "full")

#212
at212.causep1 <- dplyr::filter(abb.s2, AccidentType == 212 & CauseP1 == "24")
at212 <- at212.causep1

#221
at221.p2 <- dplyr::filter(abb.s2, AccidentType == 221 & Participant2 == "Bicylce1" | AccidentType == 221 & Participant2 == "Bicycle2")
at221 <- at221.p2


#222
at222.p2 <- dplyr::filter(abb.s2, AccidentType == 222 & Participant2 == "Bicylce1")
at222.causep1 <- dplyr::filter(abb.s2, AccidentType == 222 & CauseP1 == "24")
at222 <- plyr::join(at222.p2, at222.causep1, by = "ID", type ="full")


#223 (nachtraeglich korrigiert)
at223.p2 <- dplyr::filter(abb.s2, AccidentType == 223 & Participant2 == "Ped1")
#at223.sw <- dplyr::filter(abb.s2, AccidentType == 223 & Sidewalk == "1") #removed, feature not plausible 
at223.causep1 <- dplyr::filter(abb.s2, AccidentType == 223 & CauseP1 == "24")

#at223.1 <- plyr::join(at223.p2, at223.sw, by = "ID", type ="full")
#at223.2 <- plyr::join(at223.1, at223.causep1, by = "ID", type = "full")
#at223 <- at223.2
at223 <- plyr::join(at223.p2, at223.causep1, by = "ID", type = "full")
str(at223)

#224 (nachtraeglich korrigiert)
#at224.sw <- dplyr::filter(abb.s2, AccidentType == 224 & Sidewalk == "1") #removed, feature not plausible 
at224.causep1 <- dplyr::filter(abb.s2, AccidentType == 224 & CauseP1 == "24")
#at224 <- plyr::join(at224.sw, at224.causep1, by ="ID", type ="full")
at224 <- at224.causep1
str(at224)

#231
at231.ct <- dplyr::filter(abb.s2, AccidentType == 231 & CollisionType == "4")
at231 <- at231.ct


#232
at232.ct <- dplyr::filter(abb.s2, AccidentType == 232 & (CollisionType == "2" | CollisionType == "3"))
at232.causep1 <- dplyr::filter(abb.s2, AccidentType == 232 & CauseP1 == "4" )
at232 <- plyr::join(at232.ct, at232.causep1, by = "ID", type ="full")

#233
at233.causep1 <- dplyr::filter(abb.s2, AccidentType == 233, CauseP1 == "4")
at233 <- at233.causep1


#241
at241.p2 <- dplyr::filter(abb.s2, AccidentType == 241 & (Participant2 == "OtherVehicle" | Participant2 == "Bicylce1"))
at241.ct <- dplyr::filter(abb.s2, AccidentType == 241 & (CollisionType == "4" | CollisionType == "6"))
at241.causep2 <- dplyr::filter(abb.s2, AccidentType == 241 & CauseP2 == "7")

at241.1 <- plyr::join(at241.p2, at241.ct, by = "ID", type ="full")
at241.2 <- plyr::join(at241.1, at241.causep2, by ="ID", type ="full")
at241 <- at241.2


#242
at242.p2 <- dplyr::filter(abb.s2, AccidentType == 242 & (Participant2 == "Car1" | Participant2 == "Bicylce1" | Participant2 == "Bicycle2"))
at242.ct <- dplyr::filter(abb.s2, AccidentType == 242 & (CollisionType == "2" | CollisionType == "6"))
at242 <- plyr::join(at242.p2, at242.ct, by ="ID", type ="full")

#243
at243.ct <- dplyr::filter(abb.s2, AccidentType == 243 & CollisionType == "7")
at243 <- at243.ct


#244
at244.ct <- dplyr::filter(abb.s2, AccidentType == 244 & CollisionType == "7")
at244.p2 <- dplyr::filter(abb.s2, AccidentType == 244 & (Participant2 == "Ped1" | Participant2 == "Ped2"))
at244.causep1 <- dplyr::filter(abb.s2, AccidentType == 244 & CauseP1 == "4")

at244.1 <- plyr::join(at244.ct, at244.p2, by = "ID", type ="full")
at244.2 <- plyr::join(at244.1, at244.causep1, by = "ID", type ="full")
at244 <- at244.2

#262
at262.p2 <- dplyr::filter(abb.s2, AccidentType == 262 & Participant2 == "Ped1")
at262 <- at262.p2

#271
at271.causep1 <- dplyr::filter(abb.s2, AccidentType == 271 & CauseP1 == "30")
at271 <- at271.causep1


#274
at274.p2 <- dplyr::filter(abb.s2, AccidentType == 274 & Participant2 == "Car1")
at274.ct <- dplyr::filter(abb.s2, AccidentType == 274 & CollisionType == "6")
at274 <- plyr::join(at274.p2, at274.ct, by ="ID", type ="full")


#275 
at275.p2 <- dplyr::filter(abb.s2, AccidentType == 275 & Participant2 == "Bicylce1")
at275.ct <- dplyr::filter(abb.s2, AccidentType == 275 & CollisionType == "6")
at275 <- plyr::join(at275.p2, at275.ct, by ="ID", type ="full")


#284
at284.p2 <- dplyr::filter(abb.s2, AccidentType == 284 & (Participant2 == "Bicylce1" | Participant2 == "Car1"))
at284 <- at284.p2


#Bind all accidents with anomalies 
all.anomalies <- rbind(at203, at211, at212, at221, at222, at223, at224, at231, at232, at233, at241, at242, at243, at244, at262, at271, at274, at275, at284)


saveRDS(all.anomalies, paste(ergebnisse, "ManualDetection_Anomalies.R", sep = ""))

```



# (6) Anomaly detection using isolation forest 

```{r IF anomalies}

library(isotree)
library(dplyr)


#Interpretation: 
# A score colose to 1 indicates anomalies
# Score much smaller than 0.5 indicates normal observations
# If all scores are close to 0.5 then the entire sample does not seem to have clearly distinct values. 

#The Isolation Forest is considered individually for each two-digit accident type, as there are different correlating variables in each case. 


###########################################Prepare data-sets############################################################################

#Removal of data records containing less than 5 entries, as IsolationForest requires at least 5 cases per class.
#Determination of accident type frequencies 
at.hist <- as.data.frame(table(abb.s2$AccidentType))
colnames(at.hist) <- c("AccidentType", "Freq")
at.hist.min <- at.hist[at.hist$Freq <= 5, ]

#save
abb.s2.iso <- abb.s2

#Removal of accident types that occur too rarely. 
for(i in 1:nrow(at.hist.min)){
  
  abb.s2.iso <- subset(abb.s2.iso, AccidentType != at.hist.min[i, 1])
  
}


#Prepare the individual data sets
at20 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 20) %>% dplyr::select(ID, AccidentType, CauseP1, CauseP2, CollisionType, Participant2) %>% group_split(AccidentType)

at21 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 21) %>% dplyr::select(ID, AccidentType, CauseP1, CauseP2) %>% group_split(AccidentType)

at22 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 22) %>% dplyr::select(ID, AccidentType, CauseP1, CauseP2, CollisionType, CyclePath, Participant2, PropertyDamage, Sidewalk) %>% group_split(AccidentType)

at23 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 23) %>% dplyr::select(ID, AccidentType, CauseP1, CauseP2, CollisionType, CyclePath, Participant2, PropertyDamage) %>% group_split(AccidentType)

at24 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 24) %>% dplyr::select(ID, AccidentType, CauseP1, CauseP2, CollisionType, CyclePath, Participant2, PropertyDamage, Sidewalk) %>% group_split(AccidentType)

at25 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 25) %>% dplyr::select(ID, AccidentType, AgeP1, AgeP2, CauseP1, CollisionType, Hour, InjuryP2, Month, Participant2, PropertyDamage, Rural, SpeedLimit, StreetClass, TextLength, Urban, Weekday, WordCount) %>% group_split(AccidentType)

at26 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 26) %>% dplyr::select(ID, AccidentType, CauseP1, Hour, Participant2, Year) %>% group_split(AccidentType)

at27 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 27) %>% dplyr::select(ID, AccidentType, AgeP1, AgeP2, CauseP1, CauseP2, CollisionType, CyclePath, HitAndRun, Hour, InjuryP1, InjuryP2, LightCondition, LightlyInjured, Month, Obstacle, Participant2, PropertyDamage, SeriouslyInjured, Sidewalk, SpeedLimit, StreetClass, TextLength, Weekday, WordCount, Year) %>% group_split(AccidentType)

at28 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 28) %>% dplyr::select(ID, AccidentType, CauseP1, CauseP2, CollisionType, CyclePath, Hour, InjuryP1, LightlyInjured, Month,Participant2, PropertyDamage, Sidewalk, Weekday) %>% group_split(AccidentType)

at29 <- abb.s2.iso %>% dplyr::filter(AccidentType2 == 29) %>% group_split(AccidentType)

#Liste mit DataFrames, über die iteriert werden kann 
atl <- list(at20, at21, at22, at23, at24, at25, at26, at27, at28, at29)



###########################################Isolation-Forest-Functions############################################################################



#Function for calculating the isolationForests
calculateIsoTree <- function(x, NDIM, NTREES, NTHREADS, SAMPLE, PROBPICKPOOLEDGAIN, WEIGHKURTOSIS){
  
  #libraries
  library(isotree)
  library(dplyr)
  library(data.table)
  
  #Subsampling not used 
#  if(nrow(x) <= 256*2){
  
  #Calculate IF
  score <- as.data.frame(isotree::isolation.forest(x, ndim = NDIM, ntrees = NTREES, nthreads = NTHREADS, prob_pick_pooled_gain = PROBPICKPOOLEDGAIN, weigh_by_kurtosis = WEIGHKURTOSIS, missing_action = "fail", output_score = TRUE)$scores)
  
#  }else {
    
      #Calculate IF 
#  score <- as.data.frame(isotree::isolation.forest(x, sample_size = 20, ndim = NDIM, ntrees = NTREES, nthreads = NTHREADS, prob_pick_pooled_gain = PROBPICKPOOLEDGAIN, weigh_by_kurtosis = WEIGHKURTOSIS, missing_action = "fail", output_score = TRUE)$scores)
    
    
#  }
  
  #Add ID 
  df <- cbind(score, x$ID)
  
  #Add 2AT
  df$AccidentType2 <- substr(x$AccidentType, 1, 2)
  
  #Add 3AT
  df$AccidentType <- x$AccidentType
  
  #Add column names
  colnames(df) <- c("Score", "ID", "AccidentType2", "AccidentType")
  
  df <- dplyr::select(df, ID, Score, AccidentType2, AccidentType)
    
  return(df)  

}


#Function for calculating outliers

outliers.isolation <- function(y, z){
  
  library(ggplot2)
  library(dplyr)
  
  #Create a boxplot from the determined IsolationScores to determine the upper limit values outside the whisker. 
  x <- y %>% 
    ggplot2::ggplot(mapping = aes(x = AccidentType, y = Score))+
    geom_boxplot()
  
  #x = Diagramm (Boxplot)
  #y = DataFrame mit Scores
  #z = Grenzwert, wie hoch der Outlier-Score mindestens sein sollte. 
  
  #Data Frame with results
  limits <- as.data.frame(ggplot2::ggplot_build(x)$data[1])
  
#  AccidentType2 <- seq(20, 29, 1)
  
  #Get labels 
  AccidentType <- sort(unique(x$data$AccidentType))
  
#  limits <- cbind(limits, AccidentType2)
 
  limits <- cbind(limits, AccidentType)
   
#  limits <- dplyr::select(limits, AccidentType2, ymax)
 
  limits <- dplyr::select(limits, AccidentType, ymax)
   
  #Combine box plot limits with scores 
  comb <- plyr::join(y, limits, type = "left")
  
  #Filter outliers using the boxplot limits

#  outliers <- dplyr::filter(comb, Score >= ymax & Score >= z )

 # return(outliers)
  
  return(comb)
  
}


outliers.filter <- function(comb, z){
  
  
  library(dplyr)
  
  #Filter outliers using the boxplot limits and the z limit value
  outliers <- dplyr::filter(comb, Score >= ymax & Score >= z )

  return(outliers)
  
}



#Calculate outliers


#Iterate over list with calculation of IsolationForests per DataFrame
#x, NDIM, NTREES, NTHREADS, SAMPLE, PROBPICKPOOLEDGAIN, WEIGHKURTOSIS
#Standardparametrierung: x, NDIM=1, NTREES = 100, NTHREADS = 1, SAMPLE = NROW(df), PROBPICKPOOLEDGAIN = 0, WEIGHKURTOSIS = FALSE



#Overal function

outlier.detection <- function(x, limitmin, NTREE){
  
  
  #Detect
  iso <- data.table::rbindlist(lapply(x, calculateIsoTree,NDIM = 1, NTREES = NTREE, NTHREADS = 1, PROBPICKPOOLEDGAIN = 0, WEIGHKURTOSIS = FALSE ))
  

  #Score
  iso.out <- outliers.isolation(iso, limitmin)
  

return(iso.out)
 
  }

#Loop via list with all groups and execute the individual functions 


outliers.viz <- function(x, LIMITMIN, NT){
  
  result <- lapply(x, outlier.detection, limitmin = LIMITMIN, NTREE = NT)
  
  result.bind <- as.data.frame(data.table::rbindlist(result))
  
    
  #Filter for limits 
  result.filter <- outliers.filter(result.bind, LIMITMIN)
  
  
  #Color tables
  
  color_table <- tibble::tibble(
  AccidentType2 = c("20", "21", "22", "23", "24","25", "26", "27", "28", "29"),
  Color = c("sienna", "skyblue", "slateblue", "slategray", "springgreen", "springgreen4", "violet", "wheat", "yellow", "tan2")
  )
  
  
  
  #Create boxplot
  library(ggplot2)
  
    d.iso <- result.bind %>%
    ggplot2::ggplot(mapping = aes(x = AccidentType, y = Score))+
    geom_boxplot()+
    theme_bw()+
    #Plotten der Datenpunkte im Boxplot 
    geom_jitter(alpha = 0.11, width = 0.11, color ="grey50")+
    #Plotten der Ausreisser pro Unfalltyp
   geom_point(data = result.filter, aes (x = AccidentType, y = Score), color = "black")+
    #Kippen der x-AchsenBeschriftung
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7))+
    #Einzeichnung des festen Grenzwertes
    geom_hline(yintercept = LIMITMIN, color = "black")+
    xlab("Accident Type (3 digits, 3AT)")+
    ylab("Isolation Score")+
    scale_y_continuous(breaks = seq(0,1, 0.1), limits = c(0.3,0.8))


    ggplot2::ggsave(d.iso, file = paste(abbildungen,"Boxplot_IsolationForest_Scores_V2.png", sep = ""))
    
    plot(d.iso)
  
  
  return(result.filter)
}


##############################################################################################################################################
###########################All IF functions für Isolation-Forest (All in One)###################################################################

#Tuning the outlier limit and the number of trees 
outliers.iso <- outliers.viz(atl, 0.6, 1000)

#Number of outliers
nrow(outliers.iso)
#Inspection 
View(outliers.iso)



#Speichern
#saveRDS(outliers.iso, paste(ergebnisse, "IsolationForest_Outliers.R", sep = ""))


outliers.iso



```


# (7) Comparing Anomalies detected by manual selection and by IsolationForest

```{r Comparing anomalies}

# Read data 
abb.s2 <- readRDS(paste(ergebnisse, " 02_RP_Unfalltyp2.rds", sep =""))


#Read IF outliers 
outliers.iso <- readRDS(paste(ergebnisse, "IsolationForest_Outliers.R", sep = ""))
nrow(outliers.iso) #235

#Read manually detected outliers
outliers.man <- readRDS(paste(ergebnisse, "ManualDetection_Anomalies.R", sep = ""))
nrow(outliers.man) #94

#Compare outliers in both data-sets

plyr::join(outliers.man, outliers.iso, by = c("ID", "AccidentType"), type = "inner")


#Check, if IDs fit
outliers.iso[outliers.iso$ID == 3357, ]
outliers.man[outliers.man$ID == 3357, ]
abb.s2[abb.s2$ID == 3357, ]

#Summary of all IDs with outliers in a common vector (only unique IDs)
outliers.man.iso <- unique(c(outliers.man$ID, outliers.iso$ID))

#Removal of outliers from the basic data set
abb.s3 <- abb.s2[- outliers.man.iso, ] #7313 Unfaelle bleiben uebrig, da 309 Anomalien entfernt wurden. 


#Save data-set without anomalies 
saveRDS(abb.s3, paste(ergebnisse, " 03_RP_Unfalltyp2.rds", sep =""))


#Final processing of the results through anomaly detection

at.before <- as.data.frame(table(abb.s2$AccidentType))
at.after <- as.data.frame(table(abb.s3$AccidentType))
at.red <- at.before-at.after

at.overview <- cbind(at.before, at.after$Freq, at.red$Freq)
colnames(at.overview) <- c("AccidentType", "Freq.before", "Freq.after", "Freq.red")
at.overview$Perzentage <- round((at.overview$Freq.red / at.overview$Freq.before)*100, 2)

at.overview


dat.overview <- at.overview %>% 
  ggplot2::ggplot(mapping = aes( x = AccidentType, y = Perzentage))+
  geom_col()+
  #geom_point()+
   geom_text(aes(label = Freq.after), hjust = -0.5, size = 2)+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7))+
  xlab("Accident Type (3 digits)")+
  ylab("% of anomalies removed; Labels describe number of cases after removal")+
  coord_flip()
  
ggplot2::ggsave(dat.overview, file = paste(abbildungen,"Anomalies_Percentage_Removal.png", sep = ""))


#Descriptive description of outliers 
at.iso <- as.data.frame(table(outliers.iso$AccidentType))

#Calculate percentage
at.iso$Percentage <- round((at.iso$Freq/ sum(at.iso$Freq))*100,2)

#Sort
at.iso[order(-at.iso$Percentage), ]

at.iso[at.iso$Percentage == 0.00, ] 
```



# (8) Dataset splitting 

```{r Dataset splitting }
#Splitting of the dataset into train, test and validation data. 

library(caret)
library(dplyr)

#Read data-set without anomalies 
abb.s3 <- readRDS(paste(ergebnisse, " 03_RP_Unfalltyp2.rds", sep =""))
abb.s3 #7313 Laenge 

#Read data with accident description 
abb.s1 <- readRDS(paste(ergebnisse, "01_RP_Unfalltyp2.rds"))
abb.s1 <- dplyr::select(abb.s1, ID, Description)

#Assignment of the data set with accident description to the data set adjusted for anomalies (t = text)
abb.s3t <- plyr::join(abb.s3, abb.s1, type = "left")
saveRDS(abb.s3t, paste(ergebnisse, "03_RP_Unfalltyp2Text.rds", sep = ""))



validIndex <- caret::createDataPartition(abb.s3t$AccidentType, p = .85, list = FALSE, times = 1)
#225, 273, 279, 289 have a single records and will be selected for the sample

testtrain <- abb.s3t[validIndex, ]
abb.s3t.valid <- abb.s3t[-validIndex, ]

trainIndex <- caret::createDataPartition(testtrain$AccidentType, p = .83, list = FALSE, times = 1)
#225, 273, 279, 289 have a single records and will be selected for the sample

abb.s3t.train <- testtrain[trainIndex, ]
abb.s3t.test <- testtrain[-trainIndex, ]

#Read lengths
abb.s3t.train #5198
abb.s3t.test #1039
abb.s3t.valid #1076

#Speichern
saveRDS(abb.s3t.train, paste(ergebnisse, "04_RP_Unfalltyp2TRAIN.rds", sep = ""))
writexl::write_xlsx(abb.s3t.train, paste(ergebnisse, "04_RP_Unfalltyp2TRAIN.xlsx", sep = ""))
saveRDS(abb.s3t.test, paste(ergebnisse, "04_RP_Unfalltyp2TEST.rds", sep = ""))
writexl::write_xlsx(abb.s3t.test, paste(ergebnisse, "04_RP_Unfalltyp2TEST.xlsx", sep = ""))
saveRDS(abb.s3t.valid, paste(ergebnisse, "04_RP_Unfalltyp2VALID.rds", sep = ""))
writexl::write_xlsx(abb.s3t.valid, paste(ergebnisse, "04_RP_Unfalltyp2VALID.xlsx", sep = ""))


#Saving the pure texts for NLP feature generation
abb.s3t.test.text <- dplyr::select(abb.s3t.test, Description)
abb.s3t.valid.text <- dplyr::select(abb.s3t.valid, Description)
abb.s3t.train.text <- dplyr::select(abb.s3t.train, Description)


writexl::write_xlsx(abb.s3t.train.text, paste(ergebnisse, "04_RP_Unfalltyp2TrainText.xlsx", sep = ""))
writexl::write_xlsx(abb.s3t.test.text, paste(ergebnisse, "04_RP_Unfalltyp2TestText.xlsx", sep = ""))
writexl::write_xlsx(abb.s3t.valid.text, paste(ergebnisse, "04_RP_Unfalltyp2ValidText.xlsx", sep = ""))


#Visualisation
plot.train <- abb.s3t.train %>%
  ggplot2::ggplot((aes(x = AccidentType))) +
  geom_bar()+
  #Kippen der x-AchsenBeschriftung
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7))+
  xlab("Train: Accident Type (3 digits)")+
  ylab("Frequency")
  

plot.test <- abb.s3t.test %>%
  ggplot2::ggplot((aes(x = AccidentType))) +
  geom_bar()+
  #Kippen der x-AchsenBeschriftung
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7))+
  xlab("Test: Accident Type (3 digits)")+
  ylab("Frequency")
  

plot.valid <- abb.s3t.valid %>%
  ggplot2::ggplot((aes(x = AccidentType))) +
  geom_bar()+
  #Kippen der x-AchsenBeschriftung
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 7))+
  xlab("Validation: Accident Type (3 digits)")+
  ylab("Frequency")
  

#Show diagrams in grid 
split.grid <- cowplot::plot_grid(plot.train, plot.test, plot.valid)

ggplot2::ggsave(split.grid, file = paste(abbildungen, "04_RP_AccidentType_Histogram_TrainTestValidGrid.png", sep = ""))


```

